//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSClock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSClock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;id&quot;: 833,
        ///        &quot;name&quot;: &quot;Ḩeşār-e Sefīd&quot;,
        ///        &quot;state&quot;: &quot;&quot;,
        ///        &quot;country&quot;: &quot;IR&quot;,
        ///        &quot;coord&quot;: {
        ///            &quot;lon&quot;: 47.159401,
        ///            &quot;lat&quot;: 34.330502
        ///        }
        ///    },
        ///    {
        ///        &quot;id&quot;: 2960,
        ///        &quot;name&quot;: &quot;‘Ayn Ḩalāqīm&quot;,
        ///        &quot;state&quot;: &quot;&quot;,
        ///        &quot;country&quot;: &quot;SY&quot;,
        ///        &quot;coord&quot;: {
        ///            &quot;lon&quot;: 36.321911,
        ///            &quot;lat&quot;: 34.940079
        ///        }
        ///    },
        ///    {
        ///        &quot;id&quot;: 3245,
        ///        &quot;name&quot;: &quot;Taglag&quot;,
        ///        &quot;state&quot;: &quot;&quot;,
        ///        &quot;country&quot;: &quot;IR&quot;,
        ///        &quot;coord [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string city_list {
            get {
                return ResourceManager.GetString("city.list", resourceCulture);
            }
        }
    }
}
